### ISSUE TITLE
Hide the default configuration/data directory?

### ISSUE THREAD

**Issue by qtfkwk** [wiseaidev/ipcap#16]
IMHO, the default configuration/data directory should be either `~/.ipcap` or `~/.config/ipcap` not `~/ipcap`. I'm aware I can use the `IPCAP_FILE_PATH` environment variable, but this should be used when the directory is located somewhere else.

**Comment by wiseaidev** [comment]
Hello @qtfkwk! Agreed on this naming convention. Feel free to contribute! PRs are open!

**Comment by qtfkwk** [comment]
Actually, it should be the data local dir not config since it's data not config...
